@base = http://localhost:8080/foreach


# Etudiants =========================================

GET {{base}}/etudiants HTTP/1.1

###

GET {{base}}/etudiants/1 HTTP/1.1

###

POST {{base}}/etudiants HTTP/1.1
content-type: application/json

{
    "nom": "Michel",
    "prenom": "michel",
    "email": "michel@michel.com",
    "telephone": "06666007"
}

###

PATCH {{base}}/etudiants/4 HTTP/1.1
content-type: application/json

{
    "nom": "Michel",
    "email": "michel@newmichel.com"
}

###

DELETE {{base}}/etudiants/20 HTTP/1.1

###

# Formateurs =========================================

GET {{base}}/formateurs HTTP/1.1

###

POST {{base}}/formateurs HTTP/1.1
content-type: application/json

{
    "nom": "Michel",
    "prenom": "michel",
    "email": "michel@michel.com",
    "telephone": "06666007"
}

###

PATCH {{base}}/formateurs/6 HTTP/1.1
content-type: application/json

{
    "nom": "Michel",
    "email": "michel@michel.com"
}

###

DELETE {{base}}/formateurs/5 HTTP/1.1

###

# Cours =========================================

GET {{base}}/cours HTTP/1.1

###

GET {{base}}/cours/1 HTTP/1.1

###

POST {{base}}/cours HTTP/1.1
content-type: application/json

{
    "dateDebut": "2024-10-10T00:00:00",
    "dateFin": "2024-10-11T00:00:00",
    "ue": { "id": "1" },
    "formateur": { "id": "1" }
}

###

PATCH {{base}}/cours/1 HTTP/1.1
content-type: application/json

{
    "formateur": { "id": "6" }
}

###

DELETE {{base}}/cours/1 HTTP/1.1

###

# Absences =========================================

GET {{base}}/absences HTTP/1.1

###

GET {{base}}/absences/1 HTTP/1.1

###

POST {{base}}/absences HTTP/1.1
content-type: application/json

{
    "dateDebut": "2024-12-10T00:00:00",
    "dateFin": "",
    "type": "Vacances",
    "etudiant": { "id": "1" }
}

###

PATCH {{base}}/absences/6 HTTP/1.1
content-type: application/json

{
    "dateFin": "2024-10-11T00:00:00"
}

###

DELETE {{base}}/absences/4 HTTP/1.1
