@base = http://localhost:8080/foreach


# Etudiants =========================================

GET {{base}}/etudiants HTTP/1.1

###

POST {{base}}/etudiants HTTP/1.1
content-type: application/json

{
    "nom": "Michel",
    "prenom": "michel",
    "email": "michel@michel.com",
    "telephone": "06666007"
}

###

PATCH {{base}}/etudiants/4 HTTP/1.1
content-type: application/json

{
    "nom": "Michel",
    "email": "michel@newmichel.com",
}

###

DELETE {{base}}/etudiants/20 HTTP/1.1
